language: ruby
rvm:
  - 1.9.3

gemfile:
  - spec/support/gemfiles/Gemfile.chef10
  - spec/support/gemfiles/Gemfile.chef11

env:
  - RUBYOPT=W0

before_script:
  - ln -s chef-gitlabhq ../gitlabhq
  - mkdir -p tmp/cookbooks
  - git clone git://github.com/fnichol/chef-rvm.git tmp/cookbooks/rvm
  - git clone git://github.com/hw-cookbooks/chef_gem.git tmp/cookbooks/chef_gem
