language: ruby
rvm:
  - 1.9.3
  - 1.8.7

gemfile:
  - spec/support/gemfiles/Gemfile.chef10
  - spec/support/gemfiles/Gemfile.chef11

before_script:
  - ln -s chef-gitlabhq ../gitlabhq
  - mkdir -p tmp/cookbooks
  - git clone git://github.com/fnichol/chef-rvm.git tmp/cookbooks/rvm
  - git clone git://github.com/hw-cookbooks/chef_gem.git tmp/cookbooks/chef_gem
  - if echo $RUBY_VERSION | grep 1.8.7 >/dev/null; then rvm rubygems 1.8.25; gem --version; fi
